### ISSUE TITLE
Game stuck on 5fps

### ISSUE THREAD

**Issue by hemisemidemipresent** [touhouworldcup/thprac#117]
This seems to only be a me issue, so perhaps it could have been some setting somewhere, but when running *any* touhou game with thprac it just runs at 5fps instead of 60. Sorry for lack of specifics but honestly I don't have many ideas, I don't have any additional antivirus or anything,

Using latest version of thprac

**Comment by 32th-System** [comment]
A few people have been getting very bad performance issues with the latest thprac. Usually, what developers do to fix performance problems is to use a profiler, a program that monitors how a program runs and tells the developer what code is slowing things down the most. However, not everyone seems to be getting these performance issues. I don't seem to be getting them either.

Since this seems to be an issue that affects some users but not others, I'll need one of the affected users to run the profiler and send me the results. Because I'm not getting these issues, I don't trust the results of my own profiling.

As a result of this, here is what I want you to do:
- Download [Luke Stackwalker](https://sourceforge.net/projects/lukestackwalker/files/latest/download). This is a profiler that anyone can install and use no matter how their system is set up.
- Run the game with thprac and bring the performance down to 1 fps.
- Open Luke Stackwalker and select "Profile" > "Run"
- Select the name of your Touhou game exe from the list of processes.
- First, wait for the loading bar to fill up, then wait again to let it collect samples (let it do that for however long you want). It's good if the game is slow during the entire time Luke Stackwalker is collecting samples
- Once you stop collecting samples, click on "Save profile data" (which is the third icon in the bar with the icons and looks like a floppy disk) and send me the lsd file you get

**Comment by Mariox222** [comment]
[lsds.zip](https://github.com/touhouworldcup/thprac/files/9789825/lsds.zip)
I have the same issue. Here are 2 lsd files done with like stackwalker. 
In the first case I sampled the thprac process itself with no touhou game running. Thprac was idling on the game list. It had high CPU usage and was feeling unresponsive but it was working properly. File name "no_game_running.lsd"

In the second case I sampled th08 process with thprac attached. The game was running at 2-3 fps constantly. Main menu demo was playing during sampling. th08 process was having the same CPU usage as thprac process in the first case which is higher than normal. Thprac process in this game had next to none CPU usage.

Other details:
thprac version in the samples is the latest; 2.2.0.0.
The result is the same on older thprac versions. Restarting my pc or thprac didn't work. The same thprac executable was working 2 weeks ago, I got this issue after that 2 week break of not playing. Windows "anti malware executable" was active with high CPU usage the whole time. Th08 works fine without thprac.
system specs:
Processor	Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz   2.50 GHz
Installed RAM	8.00 GB (7.89 GB usable)
System type	64-bit operating system, x64-based processor
GPU		        NVIDIA GeForce GTX 1050

**Comment by hemisemidemipresent** [comment]
[profiler.zip](https://github.com/touhouworldcup/thprac/files/9790976/profiler.zip)

this was attatched to th13

thprac version: 2.2.0.0 (latest), very similar situation happened to older versions too

**Comment by 32th-System** [comment]
I've published a new version with a fix. If this issue no longer happens, I'll close the issue

**Comment by hemisemidemipresent** [comment]
its fixed for me, not sure about others so i wont close for now
